feat: include `_airbyte_emitted_at` in all matviews (where applicable)
community-tech-alliance/dbt-cta pull request #142
Opened 2023-05-11 18:55 UTC by emily-flambe

The only exception here is a few matviews in freshdesk that are defined by unnesting fields from a base table (`conversation_*_email.sql`).

2023-05-11 18:57 UTC, emily-flambe commented
@jitoquinto we have a request to include a timestamp reflecting the time of the sync in all our airbyte syncs. We had a handful of models that were omitting this from the final materialized views, so I went and added `_airbyte_emitted_at` to all of them where possible (I saw three matviews in `freshdesk` that were unnesting a base table, and I think it's fine to leave the timestamp field out of those for now).

This isn't in a JIRA ticket, just something I wanted to knock out quickly - will trigger the affected syncs in dev to make sure it all works 👀

2023-05-11 20:32 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/canned_response.sql
> +SELECT * FROM {{ source('cta', 'canned_response_base') }}  _airbyte_emitted_at,
this  doesnt seem right 🤔

2023-05-11 20:32 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/canned_response_folder.sql
> +SELECT * FROM {{ source('cta', 'canned_response_folder_base') }}  _airbyte_emitted_at,
same here

2023-05-11 20:33 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/discussion_comment.sql
> +SELECT * FROM {{ source('cta', 'discussion_comment_base') }}  _airbyte_emitted_at,
and here

2023-05-11 20:33 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/discussion_topic.sql
> +SELECT * FROM {{ source('cta', 'discussion_topic_base') }}  _airbyte_emitted_at,
++

2023-05-11 20:33 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/product.sql
> +SELECT * FROM {{ source('cta', 'product_base') }}  _airbyte_emitted_at,
++

2023-05-11 20:34 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/ticket_field.sql
> +SELECT * FROM {{ source('cta', 'ticket_field_base') }}  _airbyte_emitted_at,
++

2023-05-11 20:34 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/solution_folder.sql
> +SELECT * FROM {{ source('cta', 'solution_folder_base') }}  _airbyte_emitted_at,
++

2023-05-11 20:34 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/solution_category.sql
> +SELECT * FROM {{ source('cta', 'solution_category_base') }}  _airbyte_emitted_at,
++

2023-05-11 20:34 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/solution_article.sql
> +SELECT * FROM {{ source('cta', 'solution_article_base') }}  _airbyte_emitted_at,
++

2023-05-11 20:34 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/sla_policy.sql
> +SELECT * FROM {{ source('cta', 'sla_policy_base') }}  _airbyte_emitted_at,
++

2023-05-11 20:34 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/settings.sql
> +SELECT * FROM {{ source('cta', 'settings_base') }}  _airbyte_emitted_at,
++

2023-05-11 20:35 UTC, jitoquinto commented on dbt-cta/freshdesk/models/2_partner_matviews/scenario_automation.sql
> +SELECT * FROM {{ source('cta', 'scenario_automation_base') }}  _airbyte_emitted_at,
++

2023-05-11 20:36 UTC, jitoquinto requested changes
There are some files that the column got appended to the sql files even though they already have `select *`.

2023-05-12 12:26 UTC, emily-flambe commented
Oop! Well this is why we have code review lol - I'll address today!

On Thu, May 11, 2023, 4:36 PM Jesus Toquinto ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> There are some files that the column got appended to the sql files even
> though they already have select *.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/community-tech-alliance/dbt-cta/pull/142#pullrequestreview-1423397852>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALM6KBDYY44XIU5DNCMJPWDXFVEV3ANCNFSM6AAAAAAX6RBRLU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-12 14:43 UTC, emily-flambe commented
@jitoquinto I fixed the bugaboo you pointed out - before marking this ready for review, though, I've decided I'd like to take a sec to get the impacted syncs working in dev. I think some or all of them are not currently running dbt successfully in dev, and we should definitely test before applying changes to matview definitions 🤔 and I'll need to run the dbt locally first using --full-refresh to get the matview definitions to update (right?)

2023-05-12 15:16 UTC, jitoquinto commented
> @jitoquinto I fixed the bugaboo you pointed out - before marking this ready for review, though, I've decided I'd like to take a sec to get the impacted syncs working in dev. I think some or all of them are not currently running dbt successfully in dev, and we should definitely test before applying changes to matview definitions 🤔 and I'll need to run the dbt locally first using --full-refresh to get the matview definitions to update (right?)

yup i think so! could be worth a try to just run it and see if it just turns off auto-refresh without full-refresh tho?

2023-05-15 19:07 UTC, emily-flambe commented
@jitoquinto just tested all of the syncs affected by this change (using dbt commands run locally - see PR description), everything seems to check out on my end! Mind giving this another look when you have a sec? 🙏

2023-05-15 19:27 UTC, jitoquinto approved these changes

2023-05-15 19:28 UTC, merged